require("config.options")
require("config.keymaps")
require("config.lsp")
require("config.lazy")
require("config.autocmds")
require("config.session")
require("config.diagnostics")
require("config.ui2")
