return {
  'nvim-treesitter/nvim-treesitter',
  lazy = false,
  build = ':TSUpdate',
  config = function()
    require("nvim-treesitter").install({
      "bash",
      "comment",
      "css",
      "diff",
      "dockerfile",
      "fish",
      "gitcommit",
      "gitignore",
      "html",
      "ini",
      "javascript",
      "jsdoc",
      "json",
      -- "jsonc",
      "lua",
      "luadoc",
      "luap",
      "make",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "scss",
      "sql",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    })
  end
}
